// <auto-generated />
using System;
using MatchQueueService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MatchQueueService.Data.Migrations
{
    [DbContext(typeof(MatchQueueDbContext))]
    [Migration("20260429152013_CreateNotificationEnqueue")]
    partial class CreateNotificationEnqueue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MatchQueueService.Data.Entities.CategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("MatchQueueService.Data.Entities.FavoriteProductEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("account_id");

                    b.Property<string>("ProductId")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("product_id");

                    b.HasKey("AccountId", "ProductId");

                    b.ToTable("favorite_products", (string)null);
                });

            modelBuilder.Entity("MatchQueueService.Data.Entities.NotificationEnqueueEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(128)")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("account_id");

                    b.Property<bool>("Checked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("checked");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.ToTable("notification_enque", (string)null);
                });

            modelBuilder.Entity("MatchQueueService.Data.Entities.PriceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("Sale")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sale");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sale_date");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("store_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "StoreId")
                        .IsUnique()
                        .HasDatabaseName("UX_prices_product_store");

                    b.ToTable("prices", (string)null);
                });

            modelBuilder.Entity("MatchQueueService.Data.Entities.ProductEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("barcode");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("category_id");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
